apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
type: Opaque
data:
  fernet-key: IUYDCXYkc5_pzfmfHCESJGicXb9sEpV_CGfgU1BCuWA=
  executor: TG9jYWxFeGVjdXRvcg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  airflow.cfg: |
    [core]
    dags_folder = /opt/airflow/dags
    base_log_folder = /opt/airflow/logs
    # FIX: Use LocalExecutor for simplicity, matching docker-compose
    executor = LocalExecutor
    sql_alchemy_conn = postgresql://postgres:password@postgres-service:5432/nba_pipeline
    load_examples = False
    
    [webserver]
    expose_config = True
    web_server_port = 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow-webserver
        image: nba-pipeline/airflow:latest
        command: ["airflow", "webserver"]
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql://postgres:password@postgres-service:5432/nba_pipeline"
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: fernet-key
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
        - name: airflow-logs
          mountPath: /opt/airflow/logs
      - name: airflow-scheduler
        image: nba-pipeline/airflow:latest
        command: ["airflow", "scheduler"]
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql://postgres:password@postgres-service:5432/nba_pipeline"
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: fernet-key
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
        - name: airflow-logs
          mountPath: /opt/airflow/logs
      volumes:
      - name: airflow-dags
        hostPath:
          path: /path/to/nba-pipeline/airflow/dags
      - name: airflow-logs
        hostPath:
          path: /path/to/nba-pipeline/airflow/logs
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
spec:
  selector:
    app: airflow
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer