apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nba-api
  template:
    metadata:
      labels:
        app: nba-api
    spec:
      containers:
      - name: nba-api
        image: nba-pipeline/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres-service:5432/nba_pipeline"
        - name: UPSTASH_REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nba-api-service
spec:
  selector:
    app: nba-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=